# Generated by Django 4.2.1 on 2023-06-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="O'qituvchini Ism va Familiyasi",
                        max_length=255,
                        null=True,
                        verbose_name="Ism va Familiya",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("literacy", "Kompyuter savatxonligi"),
                            ("frontend", "Frontend dasturlash"),
                            ("backend", "Backend dasturlash"),
                            ("desinger", "Grafik dizeyner"),
                            ("max", "3D_Max"),
                        ],
                        default="literacy",
                        max_length=255,
                        verbose_name="Yo'nalish",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=13, null=True, verbose_name="Tel nomer"
                    ),
                ),
                (
                    "experience",
                    models.CharField(max_length=25, verbose_name="Tajribasi"),
                ),
                (
                    "img",
                    models.ImageField(
                        default="avatar_user/",
                        upload_to="",
                        verbose_name="O'qituvchini rasmi",
                    ),
                ),
                ("about", models.TextField()),
            ],
            options={
                "verbose_name": "O'qituvchi",
                "verbose_name_plural": "O'qituvchilar",
            },
        ),
    ]
