# Generated by Django 4.2.1 on 2023-06-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_alter_teacher_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="img",
            field=models.ImageField(upload_to="", verbose_name="O'qituvchini rasmi"),
        ),
    ]
