# Generated by Django 4.2.1 on 2023-06-03 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_alter_teacher_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="img",
            new_name="imga",
        ),
    ]
