# Generated by Django 4.2.1 on 2023-06-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_rename_img_teacher_imga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="imga",
            field=models.ImageField(
                default="avatar_user/", upload_to="", verbose_name="O'qituvchini rasmi"
            ),
        ),
    ]
