# Generated by Django 4.2.1 on 2023-06-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0005_alter_teacher_imga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="imga",
            field=models.ImageField(
                upload_to="teacher_img", verbose_name="O'qituvchini rasmi"
            ),
        ),
    ]
