# Generated by Django 4.2.1 on 2023-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0007_teacher_github_teacher_instagram_teacher_tg_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="instagram",
            field=models.CharField(
                default="https://instagram.com/mrit.uz?igshid=MzRlODBiNWFlZA==",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="tg_user",
            field=models.CharField(
                default="https://t.me/itparksamarkand", max_length=255, null=True
            ),
        ),
    ]
