# Generated by Django 4.2.1 on 2023-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0008_alter_teacher_instagram_alter_teacher_tg_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="direction",
            field=models.CharField(
                choices=[
                    ("Kompyuter savatxonligi", "Kompyuter savatxonligi o'qituvchisi"),
                    ("Frontend dasturlash", "Frontend dasturchi"),
                    ("Backend dasturlash", "Backend dasturchi"),
                    ("3D_Max va AuthoCAD", "3D_Max va AuthoCAD mutaxasisi"),
                    ("Grafik va Web-dizayin", "Grafik va Web-dizayin"),
                    ("SMM", "SMM mutaxasisi"),
                    ("Robototexnika", "Robototexnika mutaxasisi"),
                    ("Moushn grafika", "Moushn grafika (C4D) mutaxasisi"),
                    ("Mobil dasturlash", "Mobil dasturchi"),
                    ("IT English", "IT English o'qituvchisi"),
                ],
                default="Kompyuter savodxonligi",
                max_length=255,
                verbose_name="Yo'nalish",
            ),
        ),
    ]
