# Generated by Django 4.2.1 on 2023-06-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0009_alter_teacher_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="direction",
            field=models.CharField(
                choices=[
                    (
                        "Kompyuter savatxonligi o'qituvchisi",
                        "Kompyuter savatxonligi o'qituvchisi",
                    ),
                    ("Frontend dasturchi", "Frontend dasturchi"),
                    ("Backend dasturchi", "Backend dasturchi"),
                    ("3D_Max va AuthoCAD mutaxasisi", "3D_Max va AuthoCAD mutaxasisi"),
                    ("Grafik va Web-dizayin", "Grafik va Web-dizayin"),
                    ("SMM mutaxasisi", "SMM mutaxasisi"),
                    ("Robototexnika mutaxasisi", "Robototexnika mutaxasisi"),
                    (
                        "Moushn grafika (C4D) mutaxasisi",
                        "Moushn grafika (C4D) mutaxasisi",
                    ),
                    ("Mobil dasturchi", "Mobil dasturchi"),
                    ("IT English o'qituvchisi", "IT English o'qituvchisi"),
                ],
                default="Kompyuter savodxonligi",
                max_length=255,
                verbose_name="Yo'nalish",
            ),
        ),
    ]
