# Generated by Django 4.2.1 on 2023-06-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("itpark", "0010_park_moon"),
        ("teacher", "0010_alter_teacher_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="add",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="itpark.park"
            ),
        ),
    ]
