# Generated by Django 4.2.1 on 2023-06-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0011_teacher_add"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="add",
        ),
    ]
