# Generated by Django 4.2.1 on 2023-06-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Ism va familiya"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, unique=True, verbose_name="Pochta"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="O'quvchi holati"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "phone",
                    models.CharField(
                        max_length=13, null=True, verbose_name="Tel nomer"
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        default="avatar_user/",
                        upload_to="",
                        verbose_name="O'quvchining rasmi",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "O'quvchi",
                "verbose_name_plural": "O'quvchilar",
            },
        ),
    ]
