# Generated by Django 4.2.1 on 2023-06-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
        ("user", "0003_user_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teacher.teacher",
                verbose_name="O'qituvchi",
            ),
        ),
    ]
