# Generated by Django 4.2.1 on 2023-06-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
