# Generated by Django 4.2.1 on 2023-06-04 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_rename_img_teacher_imga"),
        ("user", "0006_alter_user_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="teacher.teacher",
                verbose_name="O'qituvchi",
            ),
        ),
    ]
