# Generated by Django 4.2.1 on 2023-06-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_remove_user_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="img",
            field=models.ImageField(
                default="avatar_user/", upload_to="", verbose_name="O'quvchining rasmi"
            ),
        ),
    ]
