# Generated by Django 4.2.1 on 2023-06-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_user_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="img",
        ),
    ]
