# Generated by Django 4.2.1 on 2023-06-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_remove_user_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="direction",
            field=models.CharField(
                choices=[
                    ("Kompyuter savatxonligi", "Kompyuter savatxonligi"),
                    ("Frontend dasturlash", "Frontend dasturlash"),
                    ("Backend dasturlash", "Backend dasturlash"),
                    ("Grafik dizeyner", "Grafik dizeyner"),
                    ("3D_Max", "3D_Max"),
                ],
                default="literacy",
                max_length=255,
                verbose_name="Yo'nalish",
            ),
        ),
    ]
