# Generated by Django 4.2.1 on 2023-06-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_user_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="img",
            field=models.ImageField(
                default="avatar_user/",
                upload_to="user_img",
                verbose_name="O'quvchining rasmi",
            ),
        ),
    ]
