# Generated by Django 4.2.1 on 2023-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_user_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("ins", models.CharField(max_length=255)),
                ("teacher", models.CharField(max_length=255)),
                ("numer", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
        ),
    ]
