# Generated by Django 4.2.1 on 2023-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_newuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="img",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
