# Generated by Django 4.2.1 on 2023-06-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_newuser_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuser",
            name="img",
        ),
    ]
