# Generated by Django 4.2.1 on 2023-06-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_alter_newuser_ins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="ins",
            field=models.CharField(max_length=255),
        ),
    ]
