# Generated by Django 4.2.1 on 2023-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_alter_newuser_ins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="message",
            field=models.TextField(
                blank=True, default="Siz IT PARKga registratsiyadan utdingiz"
            ),
        ),
    ]
