# Generated by Django 4.2.1 on 2023-06-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_alter_newuser_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuser",
            name="message",
        ),
    ]
