# Generated by Django 4.2.1 on 2023-06-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_remove_newuser_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="message",
            field=models.TextField(
                blank=True, default="Siz IT PARKga registratsiyadan utdingiz"
            ),
        ),
    ]
