# Generated by Django 4.2.1 on 2023-06-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_newuser_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
