# Generated by Django 4.2.1 on 2023-06-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuser",
            name="teacher",
        ),
    ]
