# Generated by Django 4.2.1 on 2023-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_newuser_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuser",
            name="email",
        ),
        migrations.AddField(
            model_name="newuser",
            name="ps_seria",
            field=models.CharField(max_length=9, null=True),
        ),
    ]
