# Generated by Django 4.2.1 on 2023-06-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_remove_newuser_email_newuser_ps_seria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="ps_seria",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
