# Generated by Django 4.2.1 on 2023-06-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0030_alter_newuser_ins_alter_newuser_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="vaqt",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
