# Generated by Django 4.2.1 on 2023-06-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itpark", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="park",
            name="price",
            field=models.CharField(max_length=255, null=True, verbose_name="Narxi"),
        ),
    ]
