# Generated by Django 4.2.1 on 2023-06-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itpark", "0004_alter_park_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="park",
            name="img",
            field=models.ImageField(default="avatar_user/", upload_to=""),
        ),
    ]
