# Generated by Django 4.2.1 on 2023-06-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itpark", "0005_park_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="park",
            name="about",
        ),
        migrations.RemoveField(
            model_name="park",
            name="course",
        ),
        migrations.RemoveField(
            model_name="park",
            name="img",
        ),
        migrations.RemoveField(
            model_name="park",
            name="popular_course",
        ),
        migrations.RemoveField(
            model_name="park",
            name="price",
        ),
        migrations.AddField(
            model_name="park",
            name="email",
            field=models.EmailField(
                default="nurbektemirov073@gmail.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="park",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
