# Generated by Django 4.2.1 on 2023-06-04 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "itpark",
            "0006_remove_park_about_remove_park_course_remove_park_img_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="park",
            name="email",
        ),
        migrations.RemoveField(
            model_name="park",
            name="name",
        ),
        migrations.AddField(
            model_name="park",
            name="about",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="park",
            name="course",
            field=models.CharField(
                choices=[
                    ("Kompyuter savatxonligi", "Kompyuter savatxonligi"),
                    ("Frontend dasturlash", "Frontend dasturlash"),
                    ("Backend dasturlash", "Backend dasturlash"),
                    ("Grafik dizeyner", "Grafik dizeyner"),
                    ("3D_Max", "3D_Max"),
                ],
                default=django.utils.timezone.now,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="park",
            name="img",
            field=models.ImageField(default="avatar_user/", upload_to=""),
        ),
        migrations.AddField(
            model_name="park",
            name="popular_course",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Mashhur kurslar",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="park",
            name="price",
            field=models.CharField(max_length=255, null=True, verbose_name="Narxi"),
        ),
    ]
