# Generated by Django 4.2.1 on 2023-06-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itpark", "0007_remove_park_email_remove_park_name_park_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="park",
            name="course",
            field=models.CharField(
                choices=[
                    ("Kompyuter savatxonligi", "Kompyuter savatxonligi"),
                    ("Frontend dasturlash", "Frontend dasturlash"),
                    ("Backend dasturlash", "Backend dasturlash"),
                    ("3D_Max va AuthoCAD", "3D_Max va AuthoCAD"),
                    ("Grafik va Web-dizayin", "Grafik va Web-dizayin"),
                    ("SMM", "SMM"),
                    ("Robototexnika", "Robototexnika"),
                    ("Moushn grafika", "Moushn grafika (C4D)"),
                    ("Mobil dasturlash", "Mobil dasturlash"),
                    ("IT English", "IT English"),
                ],
                max_length=255,
            ),
        ),
    ]
