# Generated by Django 4.2.1 on 2023-06-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itpark", "0009_remove_park_about_remove_park_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="park",
            name="moon",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Kurs davomiyligi"
            ),
        ),
    ]
